services:

  app:
    build: .
    container_name: klp_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_HOST: klp_db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: klp_user
      DATABASE_PASSWORD: klp_password
      DATABASE_NAME: klp_db
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: templates/
          target: /klp/templates/
        - action: sync
          path: static/
          target: /klp/static/
        - action: sync
          path: app/
          target: /klp/app/
        - action: sync
          path: main.py
          target: /klp/main.py
        - action: rebuild
          path: .
          ignore:
            - main.py
            - templates/**
            - static/**
            - app/**
            - '**/*.py'
            - '**/~*'
            - '**/.#*'
            - '**/*.swp'
            - '**/*.swpx'
            - '**/*.tmp'
            - '**/.~lock.*'
            - '**/.DS_Store'
            - README.md
            - .python-version
            - uv.lock

  db:
    image: pgvector/pgvector:pg17
    container_name: klp_db
    environment:
      POSTGRES_USER: klp_user
      POSTGRES_PASSWORD: klp_password
      POSTGRES_DB: klp_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U klp_user -d klp_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
