services:

  app:
    image: ghcr.io/justforjan/klp:latest
    container_name: klp_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: pgvector/pgvector:pg17
    container_name: klp_db
    environment:
      POSTGRES_USER: klp_user
      POSTGRES_PASSWORD: klp_password
      POSTGRES_DB: klp_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U klp_user -d klp_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
