services:

  app:
    build: .
    image: klp-app:latest
    environment:
      ENV: local_docker
    develop:
      watch:
        - action: sync
          path: templates/
          target: /klp/templates/
        - action: sync
          path: static/
          target: /klp/static/
        - action: sync
          path: app/
          target: /klp/app/
        - action: sync
          path: main.py
          target: /klp/main.py
        - action: rebuild
          path: .
          ignore:
            - main.py
            - templates/**
            - static/**
            - app/**
            - '**/*.py'
            - '**/~*'
            - '**/.#*'
            - '**/*.swp'
            - '**/*.swpx'
            - '**/*.tmp'
            - '**/.~lock.*'
            - '**/.DS_Store'
            - README.md
            - .python-version
            - uv.lock
