name: Lint Check

on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  lint-check:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Lint check (ruff)
        uses: astral-sh/ruff-action@v3
